// =============================================================================
// Module  : fast_top_tb
// Purpose : Self-checking testbench for fast_top.
//
//  Flow
//  ────
//  1. Load grayscale pixel data from  image_pixels.hex  (generated by
//     compare_fast.py — one 8-bit hex value per line, row-major order).
//  2. Drive the AXI4-Stream slave interface of fast_top one pixel per clock,
//     asserting TUSER on pixel 0 and TLAST on the last pixel of every line.
//  3. Capture every corner_valid pulse and write
//        col  row  score
//     to  rtl_corners.txt  (one corner per line, decimal integers).
//  4. Wait for the pipeline to drain.
//
//  The Python script compare_fast.py reads rtl_corners.txt and compares
//  results against OpenCV FAST.
//
// Parameters — must match the fast_top instantiation AND the Python script.
//   IMG_WIDTH   – pixels per line  
//   IMG_HEIGHT  – lines per frame   
//   THRESHOLD   – FAST threshold T  (default 35)
//   N_CONSEC    – min consecutive   (default 9 → FAST-9)
//   SCORE_WIDTH – score bus width   (default 12)
// =============================================================================

`timescale 1ns / 1ps

module fast_top_tb;

    // ── Simulation parameters ──────────────────────────────────────────────
    localparam IMG_WIDTH    = 1280;
    localparam IMG_HEIGHT   = 720;
    localparam THRESHOLD    = 35;
    localparam N_CONSEC     = 9;
    localparam SCORE_WIDTH  = 12;
    localparam TOTAL_PX     = IMG_WIDTH * IMG_HEIGHT;

    // Extra clocks after last pixel to let the full pipeline drain:
    //   6 row-buffer rows  +  3 SR column stages  +  NMS 2-row delay  +  margin
    localparam DRAIN_CYCLES = IMG_WIDTH * 12;

    // ── DUT signals ────────────────────────────────────────────────────────
    reg        clk;
    reg        rst_n;

    // AXI4-Stream slave
    reg  [7:0] s_axis_tdata;
    reg        s_axis_tvalid;
    wire       s_axis_tready;
    reg        s_axis_tlast;
    reg        s_axis_tuser;

    // Corner output
    wire                          corner_valid;
    wire [$clog2(IMG_WIDTH) -1:0] corner_col;
    wire [$clog2(IMG_HEIGHT)-1:0] corner_row;
    wire [SCORE_WIDTH-1:0]        corner_score;

    // ── DUT instantiation ──────────────────────────────────────────────────
    fast_top #(
        .IMG_WIDTH  (IMG_WIDTH),
        .IMG_HEIGHT (IMG_HEIGHT),
        .THRESHOLD  (THRESHOLD),
        .N_CONSEC   (N_CONSEC),
        .SCORE_WIDTH(SCORE_WIDTH)
    ) u_dut (
        .clk            (clk),
        .rst_n          (rst_n),
        .s_axis_tdata   (s_axis_tdata),
        .s_axis_tvalid  (s_axis_tvalid),
        .s_axis_tready  (s_axis_tready),
        .s_axis_tlast   (s_axis_tlast),
        .s_axis_tuser   (s_axis_tuser),
        .corner_valid   (corner_valid),
        .corner_col     (corner_col),
        .corner_row     (corner_row),
        .corner_score   (corner_score)
    );

    // ── Clock: 100 MHz (10 ns period) ─────────────────────────────────────
    initial clk = 0;
    always  #5 clk = ~clk;

    // ── Pixel memory (loaded from hex file) ───────────────────────────────
    reg [7:0] pixel_mem [0:TOTAL_PX-1];

    // ── Corner capture (runs in parallel with stimulus) ───────────────────
    integer f_out;
    integer corner_cnt;

    always @(posedge clk) begin
        if (corner_valid) begin
            // Write: col  row  score  (decimal, space-separated)
            $fwrite(f_out, "%0d,%0d,%0d\n",
                    corner_col, corner_row, corner_score);
            corner_cnt = corner_cnt + 1;
        end
    end

    // ── Main stimulus ──────────────────────────────────────────────────────
    integer pix_idx;
    integer col_idx;

    initial begin

        // ── Load image pixels ──────────────────────────────────────────────
        $readmemh("image_pixels.hex", pixel_mem);
        $display("[TB] Pixel memory loaded (%0d pixels, %0dx%0d)",
                 TOTAL_PX, IMG_WIDTH, IMG_HEIGHT);

        // ── Open output file ───────────────────────────────────────────────
        f_out      = $fopen("rtl_corners.txt", "w");
        corner_cnt = 0;

        if (f_out == 0) begin
            $display("[TB] ERROR: Cannot open rtl_corners.txt for writing");
            $finish;
        end

        // ── Initialise signals ─────────────────────────────────────────────
        rst_n         = 0;
        s_axis_tdata  = 8'h00;
        s_axis_tvalid = 1'b0;
        s_axis_tlast  = 1'b0;
        s_axis_tuser  = 1'b0;

        // ── Reset ──────────────────
        repeat(10) @(posedge clk);
        @(posedge clk); #1; rst_n = 1;
        repeat(5)  @(posedge clk);

        $display("[TB] Reset released. Starting pixel stream...");

        // ── Stream all pixels at pixel rate (1 pixel per clock) ───────────
        //    Drive signals 1 ns after posedge so they are stable well before
        //    the next posedge.
        for (pix_idx = 0; pix_idx < TOTAL_PX; pix_idx = pix_idx + 1) begin
            @(posedge clk); #1;
            col_idx = pix_idx % IMG_WIDTH;

            s_axis_tdata  = pixel_mem[pix_idx];
            s_axis_tvalid = 1'b1;
            // TUSER: start-of-frame — asserted only on the very first pixel
            s_axis_tuser  = (pix_idx == 0) ? 1'b1 : 1'b0;
            // TLAST: end-of-line — asserted on the last column of every row
            s_axis_tlast  = (col_idx == IMG_WIDTH - 1) ? 1'b1 : 1'b0;
        end

        // ── De-assert AXI valid after last pixel ───────────────────────────
        @(posedge clk); #1;
        s_axis_tvalid = 1'b0;
        s_axis_tlast  = 1'b0;
        s_axis_tuser  = 1'b0;
        s_axis_tdata  = 8'h00;

        $display("[TB] All %0d pixels sent. Waiting for pipeline to drain...",
                 TOTAL_PX);

        // ── Wait for all in-flight corners to propagate out ────────────────
        repeat(DRAIN_CYCLES) @(posedge clk);

        // ── Wrap up ────────────────────────────────────────────────────────
        $fclose(f_out);
        $display("[TB] Simulation done. %0d corners written to rtl_corners.txt",
                 corner_cnt);
        $finish;
    end

    // ── Timeout watchdog (prevents infinite hang) ──────────────────────────
    initial begin
        // Allow (TOTAL_PX + DRAIN_CYCLES + 200) clock cycles maximum
        #( (TOTAL_PX + DRAIN_CYCLES + 500) * 10 );
        $display("[TB] TIMEOUT — simulation exceeded maximum allowed cycles.");
        $fclose(f_out);
        $finish;
    end

endmodule
